### ISSUE TITLE
Incorrect path name returned; includes double forward slash

### ISSUE THREAD

**Issue by nathanl** [CargoSense/briefly#11]
When creating a directory, I get back an incorrect path name which contains a repeated forward slash. For example:

```elixir
Briefly.create(directory: true)
# =>
{:ok,
 "/var/folders/2w/cy9_59s505n3fzzl4b21pmdm0000gp/T//briefly-1523/briefly-357802-608488-1"}
#                                                  ^ whoops
```

Here, `T//briefly-1523` should be `T/briefly-1523`, as it actually exists in the file system.

**Comment by Schultzer** [comment]
#9 Resolves this issue

**Comment by jfcalvo** [comment]
I have seen that the last release is pretty old. Why not a release with all the latests improvements including this one?
