### ISSUE TITLE
Cannot be used by multiple users with default config

### ISSUE THREAD

**Issue by wisq** [CargoSense/briefly#16]
Since the default configuration writes to the global temporary directory, and since the top-level directory uses a standard, predictable name (based on the slowest-changing first element of `:os.timestamp`), `briefly` cannot be used by multiple users on the same system in its default configuration.

The first user to use `briefly` will create the `briefly-<timestamp>` directory, and then subsequent users will be unable to use `briefly`:

```
% ls /tmp/briefly-*
zsh: no matches found: /tmp/briefly-*


% iex -S mix
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Briefly.create()
{:ok, "/tmp/briefly-1551/briefly-456690-155484-2"}


% sudo -u other_user iex -S mix
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Briefly.create()
[error] GenServer Briefly.Entry terminating
** (CaseClauseError) no case clause matching: {:error, :eacces}
    (briefly) lib/briefly/entry.ex:96: Briefly.Entry.open/6
    (briefly) lib/briefly/entry.ex:30: Briefly.Entry.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.209.0>): {:create, []}
State: {["/tmp", "/current_directory/tmp"], #Reference<0.455748023.2892627972.57466>}
Client #PID<0.209.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:258: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
** (exit) exited in: GenServer.call(#PID<0.189.0>, {:create, []}, 5000)
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, :eacces}
            (briefly) lib/briefly/entry.ex:96: Briefly.Entry.open/6
            (briefly) lib/briefly/entry.ex:30: Briefly.Entry.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:989: GenServer.call/3
```

The location _must_ be overridden, either with the configuration or with the `TMPDIR` etc environment variables.  Also, the user's unique location must come _before_ any shared locations, since it does not fall back to other locations if it can't create the top-level `briefly-<timestamp>` directory.

Elixir doesn't seem to have an easy way to get the current user ID, but it might be worth embedding `System.get_env("UID")` in the top-level directory name, and/or making it random.

**Comment by benwilson512** [comment]
The problem is that user based behaviour would be very system dependent. This seems exactly like a situation where custom configuration should be expected. Definitely the docs could be improved here.

**Comment by wisq** [comment]
Hm, I suppose, but I've never seen a tempfile-creating function in any language that has this sort of issue.  Most of them in fact try to ensure that anything they create (directly under the temporary directory of choice) is both random and unpredictable, to avoid any sort of prediction attacks (e.g. symlinks to trick the app into writing to something it shouldn't).

(Not that I'm saying `briefly` has any such issues, just that it's generally expected that much of the point of a tempfile library is to allow multiple users to safely use world-writable temporary file directories.)
