### ISSUE TITLE
Readme, Hex and Tags disagree on latest release version

### ISSUE THREAD

**Issue by zph** [CargoSense/briefly#17]
Hello!

Thank you for Briefly, it solves some problems I'm seeing with handling tempfiles in Elixir.

The issue I saw is that the readme cites `0.4` as version, but the tags on Github show 0.3 as latest and I wasn't able to get 0.4 on hex. For now I'll pin to the head of master (2526e9674a4e6996137e066a1295ea60962712b8) but I'd prefer to pin to semvar to avoid some dependency challenges when multiple projects use Briefly.

When you get a moment, can you please resolve that? Seems like there might be local commits or private repo commits and tags that didn't make it here and to hex 👍.

Thanks!

**Comment by lpil** [comment]
Yes please! It would be great to have the latest version on Hex. :)

**Comment by vishaltelangre** [comment]
Any update on this? Version 0.4 is still missing on https://hex.pm/packages/briefly.

**Comment by InoMurko** [comment]
Ping

**Comment by zph** [comment]
@benwilson512 Would you be open to an additional maintainer to help with the repo? 👍 😄 🐱 

Happy to help out here since I had another patch in the project and deeply vested in :elixir:

Also: thank you for Absinthe! I'm enjoying it.

**Comment by warmwaffles** [comment]
@benwilson512 anything else I can do to help get this updated?

**Comment by benwilson512** [comment]
Hey folks, turns out I don't actually have hex package ownership on this one. Will resolve and try to get a release out later today.

**Comment by warmwaffles** [comment]
Thanks @benwilson512!

**Comment by sgerrand** [comment]
@benwilson512, have you had any luck with getting the requisite Hex privileges?

**Comment by mcrumm** [comment]
I just released v0.4.0 on hex :) https://hex.pm/packages/briefly/0.4.0

**Comment by zph** [comment]
Thanks @mcrumm 👍
