### ISSUE TITLE
Using Briefly with Plug.send_file

### ISSUE THREAD

**Issue by rockwood** [CargoSense/briefly#23]
I'm seeing intermittent errors in production and I'm curious if there's a potential race condition going on. 

Here's a rough idea of what I'm doing:

```elixir
# Phoenix controller

def create(conn, params)
  path = Briefly.create!()
  File.write!(path, some_content)
  send_download(conn, {:file, path})
end
```

Usually this works fine, but I'm seeing occasional requests fail with [Server Request Interrupted](https://devcenter.heroku.com/articles/error-codes#h18-server-request-interrupted). 

[Phoenix's send_download](https://github.com/phoenixframework/phoenix/blob/e82161eb8f724a69cb17b8e2a22ea54e595b29ca/lib/phoenix/controller.ex#L915) delegates to [Plug's send_file](https://github.com/elixir-plug/plug/blob/3193ab3a8e1973e2fcc37b33417724a45dac857c/lib/plug/conn.ex#L420) which states the following:

> If available, the file is sent directly over the socket using the operating system sendfile operation.

Could there be an issue where the Plug request completes, but the OS hasn't finished writing the file to the socket before  Briefly removes it? Maybe I shouldn't be using Briefly in this scenario?

I'd appreciate any insights you have. Thanks!

**Comment by srgpqt** [comment]
That's because cowboy is sending the file from another process, so briefly deletes the file before it can be sent. You must pass briefly the Plug connection pid through the monitor_pid option.

Something like this:
```elixir
    connection_pid =
      case conn.adapter do
        {Plug.Cowboy.Conn, %{pid: pid}} -> pid
        _ -> self()
      end

    path = Briefly.create!(monitor_pid: connection_pid)
```

**Comment by benwilson512** [comment]
Thanks @srgpqt !

**Comment by RodolfoSilva** [comment]
This does't work if you are using Bandit.
