### ISSUE TITLE
Crash when open doesn't have enough space on the device to create the temporary directory.

### ISSUE THREAD

**Issue by Sinc63** [CargoSense/briefly#39]
Log:
```
Apr 19 09:20:55 localhost one[7970]: [error] error_info/7:gen_server.889 GenServer Briefly.Entry terminating#012** (CaseClauseError) no case clause matching: {:error, :enospc}#012    (briefly) lib/briefly/entry.ex:85: Briefly.Entry.open/6#012    (briefly) lib/briefly/entry.ex:31: Briefly.Entry.handle_call/3#012    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4#012    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6#012    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3#012Last message (from #PID<0.9388.0>): {:create, [directory: true]}
```

Although I am apparently running a two year old version of the app (soon to be changed), the error causing this crash is still clearly visible in entry.ex/open, where the case on File.mkdir_p! has an explicit handler for two specific error case reasons but no general handler for other errors. Thus :enospc causes the app to crash instead of returning some rational failure message.

Would be great to see a quick fix before I do the update.

**Comment by benwilson512** [comment]
@Sinc63 PR welcome!

**Comment by Sinc63** [comment]
> @Sinc63 PR welcome!

@benwilson512 You're welcome.
