### ISSUE TITLE
"could not find process"

### ISSUE THREAD

**Issue by tfwright** [CargoSense/briefly#40]
Trying to use Briefly 0.3 to create a temporary file in a script attached to an application that has briefly as a dependency. The script fails with the following error:

```
(RuntimeError) could not find process Briefly.Entry. Have you started the :briefly application?\n    lib/briefly/entry.ex:6: Briefly.Entry.server/0\n    lib/briefly.ex:25: Briefly.create/1\n
```

But the docs don't mention anything about starting a process, or adding it to the application supervision tree.

**Comment by benwilson512** [comment]
PR Welcome.

**Comment by tfwright** [comment]
Happy to open a pr, but not sure exactly what the remedy is here. Just an error message change? Expanded docs? What is the recommended way to use briefly in a script?

**Comment by benwilson512** [comment]
Hi @tfwright you should probably `Briefly.start` if you want to use this in a script. An update to the docs denoting that you need to `Briefly.start` when not starting it as part of an application's dependency tree would be helpful.
